version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dashman
      POSTGRES_PASSWORD: dashm4n
    ports:
      - 5654:5432
    volumes:
      - ./data:/var/lib/postgresql/data
